labels:
  app: kapelal-blog
init:
  repo: https://github.com/test/test.git
  branch: master
blog:
  tag: latest
ingress:
  host: ingress.com
  protocol: http
#  annotations:
#    kubernetes.io/ingress.class: nginx-kapelal
